name: Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm
          registry-url: https://npm.pkg.github.com
          scope: '@void-sdk'
      - run: pnpm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      - run: pnpm void deploy
        env:
          VOID_TOKEN: ${{ secrets.VOID_TOKEN }}
